### ISSUE TITLE
License of CURL C lib need to be checked

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/tsc#30]
Our cpp-sdk depeneds on @8.6.0. The license can be found here: https://curl.se/docs/copyright.html
We need to check if we can use that license.
See https://github.com/LFDT-Hiero/tsc/issues/8 for more details.

**Comment by hendrikebbers** [comment]
The Curl license appears to be a modified MIT license that has some of the rights granted under the MIT license removed, most notably the ability to sublicense.  We need to ask a licensing lawyer whether the lack of sublicense and other rights impacts the intended use and distribution of what you are building.

**Comment by rwalworth** [comment]
https://github.com/hashgraph/hedera-sdk-cpp/issues/794 work to replace `curl` with `cpp-httplib`
