### ISSUE TITLE
Create user groups for hiero-mirror-node

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/tsc#50]
As defined in https://github.com/hiero-ledger/governance, we need to create two groups for each project: A group that contains 2-3 maintainers of the project and a group with all project committers. The groups can be added to https://github.com/hiero-ledger/governance/blob/main/config.yaml by doing a PR.

**Comment by steven-sheehy** [comment]
Can we define the difference between maintainers and committers in Hiero? It's not clear to me how to map my current groups and users should map over.

**Comment by hendrikebbers** [comment]
@steven-sheehy agree. I will add some documentation to the readme.

**Comment by hendrikebbers** [comment]
@steven-sheehy please check if this addition helps: https://github.com/hiero-ledger/governance/pull/60 In that case please approve the PR :)

**Comment by steven-sheehy** [comment]
PR https://github.com/hiero-ledger/tsc/issues/50
